#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

mknod -m 0666 /dev/nvidiactl c 195 255

# Speed up /dev/urandom initialization. Needed for Xavier only,
# so haveged is included only in its initramfs.
if [ -x /sbin/haveged ]; then
    /sbin/haveged --Foreground --verbose=1 -w 1024 &
    haveged_pid=$!
    waitrandom
    kill $haveged_pid || true
fi
