name: jetson-tx1-kernel
version: 4.4-tegra-l4t-r28.2.1
summary: nvidia Jetson TX1 kernel
description: nvidia Jetson TX1 kernel
grade: stable
confinement: strict
type: kernel
architectures: [arm64]

parts:
  kernel:
    plugin: nil
    source: ../src
    override-pull: |
      snapcraftctl pull
      # Get kernel sources, which are distributed across different repos
      mv l4t_28.2.0/source_sync.sh .
      ./source_sync.sh -k tegra-l4t-r28.2.1
      # Apply canonical patches - apparmor stuff essentially
      cd sources/kernel/display
      git am ../../../l4t_28.2.0/patch-display/*
      cd -
      cd sources/kernel/kernel-4.4
      git am ../../../l4t_28.2.0/patch/*
    override-build: |
      JETSON_KERNEL_CONFIG=tegra21_defconfig ./build.sh
    build-packages:
      - lsb-release
      - bc
      - git
      - libssl-dev
      - rsync
      - lzop
      - gcc-aarch64-linux-gnu
      - jq
      - squashfs-tools
      - curl
      - build-essential

  firmware:
    plugin: nil
    override-build: |
      set -xe
      wget https://developer.nvidia.com/embedded/dlc/l4t-jetson-tx1-driver-package-28-2-ga -O Tegra210_Linux_R28.2.0_aarch64.tbz2
      tar xf Tegra210_Linux_R28.2.0_aarch64.tbz2 Linux_for_Tegra/nv_tegra/nvidia_drivers.tbz2
      tar xf Linux_for_Tegra/nv_tegra/nvidia_drivers.tbz2 lib/firmware/
      cd lib; cp -r firmware/ "$SNAPCRAFT_PART_INSTALL"
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/firmware/gm20b
      cd "$SNAPCRAFT_PART_INSTALL"/firmware/gm20b
      ln -sf "../tegra21x/acr_ucode.bin" "acr_ucode.bin"
      ln -sf "../tegra21x/gpmu_ucode.bin" "gpmu_ucode.bin"
      ln -sf "../tegra21x/gpmu_ucode_desc.bin" "gpmu_ucode_desc.bin"
      ln -sf "../tegra21x/gpmu_ucode_image.bin" "gpmu_ucode_image.bin"
      ln -sf "../tegra21x/gpu2cde.bin" "gpu2cde.bin"
      ln -sf "../tegra21x/NETB_img.bin" "NETB_img.bin"
      ln -sf "../tegra21x/fecs_sig.bin" "fecs_sig.bin"
      ln -sf "../tegra21x/pmu_sig.bin" "pmu_sig.bin"
      ln -sf "../tegra21x/pmu_bl.bin" "pmu_bl.bin"
      ln -sf "../tegra21x/fecs.bin" "fecs.bin"
      ln -sf "../tegra21x/gpccs.bin" "gpccs.bin"

  initramfs:
    after: [ kernel, firmware ]
    plugin: nil
    source: ../initramfs
    override-build: |
      mkdir -p lib/firmware
      cp "$SNAPCRAFT_STAGE"/firmware/tegra*_xusb_firmware lib/firmware/
      find . | cpio --quiet -o -H newc | lzma >> "$SNAPCRAFT_STAGE"/initrd.img
